### ISSUE TITLE
Revamp the spriteloader and other classes

### ISSUE THREAD

**Issue by natis1** [natis1/Hitlers_Trampoline_Hero#5]
Too much bad code :(

**Comment by LSaldyt** [comment]
Lol don't worry about it that much, maybe just walk me through it once we're in person again? I had some trouble with loading sprites and with changing the elvenGameState variable to work for the BattlePanel so that I could start testing it. The code isn't really too bad, it just looks like you were testing a lot of stuff. Anyways.

**Comment by natis1** [comment]
Working on adding comments to the different modules. For now sprites take location, angle (in degrees I believe), and the location of an image OR a buffered image. Gamestate is shitty code all around but it isn't hard to use if you learn it (ima add comments) and more importantly it has a small impact on system resources so I haven't bothered to change it. Yeah better code could run 100x faster than gamestate but 100x faster than almost zero is still almost zero. I'll figure it out eventually.

**Comment by natis1** [comment]
Still need to figure out a new way to load windows but for now the spriteloader has been completely overhauled to save about 50-100 MB of RAM and has been made so one can easily add a class to load sprites of their choice.
